### ISSUE TITLE
[Feature Request] Add browser option

### ISSUE THREAD

**Issue by madhur** [omarahm3/chromrofi#4]
I would love to use it but I currently use brave most of the time.

I think we can easily extend it to support browsers such as "Firefox, Brave" etc. As far as I know, they all store the bookmarks in the same format, just the directory is different.

Hence, we can have the option to specify the browser and lookup directory becomes different.

Happy to contribute if required.

**Comment by omarahm3** [comment]
@madhur sure bro, i think firefox might be a bit different than chromium based browsers, but i will look into it

**Comment by omarahm3** [comment]
@madhur brave is now supported, with ability to almost add support for any chromium support too. So enjoy bro
